# See https://about.gitlab.com/2015/06/08/implementing-gitlab-ci-dot-yml/
before_script:
  - source ~/.bashrc
  - perlbew info
  - pushd ..
  - export CPRAN_PRAAT_DIR=$(pwd)
  - cpran deps template | cpran install
  - popd

my_job:
  script:
    - prove -v --exec "praat --ansi --pref-dir=../.. --run"
  stage: test
  only:
    - master
  except:
    - develop
  tags:
    - praat
    - cpran
