# See https://about.gitlab.com/2015/06/08/implementing-gitlab-ci-dot-yml/
my_job:
  script:
    - cpran deps template | cpran install
    - prove -v --exec "praat --ansi --pref-dir=../.. --run"
  stage: test
  only:
    - master
  except:
    - develop
  tags:
    - praat
    - cpran
